;              
CREATE USER IF NOT EXISTS "SA" SALT '049e5fc166d842b0' HASH 'c920d833a4f684f384ba0ad0d332259302b67b09c0a06ffade9ec930715e7296' ADMIN;          
CREATE MEMORY TABLE "PUBLIC"."BOX"(
    "ID" INTEGER NOT NULL,
    "CONTAINED_IN" INTEGER
);   
ALTER TABLE "PUBLIC"."BOX" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");           
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.BOX;      
INSERT INTO "PUBLIC"."BOX" VALUES
(1, NULL),
(3, 1),
(6, 1);   
CREATE MEMORY TABLE "PUBLIC"."ITEM"(
    "ID" INTEGER NOT NULL,
    "CONTAINED_IN" INTEGER,
    "COLOR" VARCHAR(100)
);        
ALTER TABLE "PUBLIC"."ITEM" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");          
-- 6 +/- SELECT COUNT(*) FROM PUBLIC.ITEM;     
INSERT INTO "PUBLIC"."ITEM" VALUES
(1, 1, NULL),
(2, 1, 'red'),
(3, 3, 'red'),
(4, 3, 'black'),
(5, 1, NULL),
(6, NULL, NULL); 
ALTER TABLE "PUBLIC"."ITEM" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_22" FOREIGN KEY("CONTAINED_IN") REFERENCES "PUBLIC"."BOX"("ID") NOCHECK;       
